Add persistent storage
Romero027/bookinfo-grpc pull request #5
Opened 2023-02-10 03:45 UTC by livingshade

TODO: 
- different storage for different version of review
- products

2023-02-10 07:02 UTC, Romero027 commented on kubernetes/apply/details/details-mongodb.yaml
> +    kompose.cmd: kompose convert
Please remove these unused kcompose annotations

2023-02-10 07:05 UTC, Romero027 requested changes
Can you merge all yaml files into a single yaml file? Ideally, we want to deploy it with just one command.

And please remove all kcompose annotations. 

Thanks!

2023-02-10 09:29 UTC, livingshade commented
> Please remove these unused kcompose annotations

Done

> Can you merge all yaml files into a single yaml file? Ideally, we want to deploy it with just one command.

A single large yaml file might be a little bit too complex? I have put them together into a folder and a single `kubectl apply -Rf ./kubernetes/apply` will do.

2023-02-11 22:23 UTC, Romero027 commented
looks good. Thanks

2023-02-11 22:24 UTC, merged